# Generated by Django 4.1 on 2022-08-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='rubrics',
            field=models.ManyToManyField(related_name='authors', to='articles.rubric'),
        ),
    ]
